language: rust

branches:
  only:
  - master
  - develop

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
    - os: windows

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --all --all-features --verbose

