language: rust

branches:
  only:
  - master

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows
  - osx

jobs:
  include:
    - stage: style
      os: linux
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
        - rustup install --force cargo-audit
      script:
        - cargo audit
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo fmt --all -- --check
    - stage: tests
      script:
         - cargo build --verbose -- --all
         - cargo build --verbose -- --examples
         - cargo test --verbose -- --all

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
