language: rust

branches:
  only:
  - master
  - develop

rust:
  - stable
  - beta
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - sudo apt-get install clang
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --all --all-features --verbose

