language: rust

branches:
  only:
  - master

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows
  - osx

jobs:
  include:
    - stage: style
      os: linux
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
        - rustup install --force cargo-audit
      script:
        - cargo audit
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo fmt --all -- --check

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --all --verbose
  - cargo build --examples --verbose
  - cargo test --all --verbose

cache: cargo
