language: rust

branches:
  only:
  - master
  - develop

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly

install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install llvm
        ;;
    esac

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --all --all-features --verbose

