[package]
name = "lv2-midi"
version = "0.1.0"
authors = ["Janonard <jan.opdenhoevel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2-midi-sys = { path = "sys" }