[package]
name = "lv2-midi"
version = "0.1.0"
authors = ["Jan-Oliver 'Janonard' Opdenhövel <jan.opdenhoevel@protonmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2-core = { path = "../core" }
lv2-urid = { path = "../urid" }
lv2-atom = { path = "../atom" }
lv2-midi-sys = { path = "sys" }

[dependencies.wmidi]
version = "3.1.0"
optional = true