[package]
name = "lv2-state"
version = "1.0.0"
authors = ["Jan-Oliver 'Janonard' Opdenhövel <jan.opdenhoevel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2-sys = { path = "../sys" }
lv2-core = { path = "../core" }
lv2-urid = { path = "../urid" }
lv2-atom = { path = "../atom" }

[features]
default = []
host = ["lv2-core/host", "lv2-urid/host", "lv2-atom/host"]