[package]
name = "lv2-atom"
version = "0.1.0"
authors = ["Janonard <jan.opdenhoevel@protonmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2-atom-sys = { path = "sys" }
lv2-core = { path = "../core" }
lv2-urid = { path = "../urid" }