name: Rust

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --all-features --verbose
