name: Rust

on:
  push:
    branches: 
    - master
    - develop
    - pregenerated-sys
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --all-features --verbose
  
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Format
      run: cargo fmt --all -- --check
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all --all-features -- -D warnings

  gen-bindings:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Generate
      run: cargo run -p gen-bindings -- -I ./sys/lv2/ -o bindings.rs
    - uses: actions/upload-artifact@v1
      with:
        name: bindings
        path: bindings.rs