name: Rust

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:
    runs-on: 
    - ubuntu-latest
    - windows-latest
    - macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --all-features --verbose
  
  verify:
    runs-on:
    - ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --all --all-features --verbose -- -D warnings
