name: Rust

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --all-features --verbose
  
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Format
      run: cargo fmt --all -- --check
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all --all-features -- -D warnings
  
  book:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install -r recommonmark sphinx sphinx_rtd_theme
    - name: Build Book
      run: |
        cd docs
        make html
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
